In [119]:
driver = webdriver.Chrome("chromedriver.exe")

In [120]:
#opening the homepage of flipkart

driver.get('https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=400001')

In [134]:
links = []


url=driver.find_elements_by_xpath('//div[@class="col-4"]/a')#scraping urls

for i in url:

    links.append(i.get_attribute("href"))#appending the urls in links list


#The empty lists for appending it later.

product_Names = []
Years = []
fuels = []
kms_drivens = []
ownerss = []
transmissions = []
prices = []

for i in links:
    driver.get(i)
    time.sleep(1)
    
    try:
        name = driver.find_element_by_xpath("//h2[@class = '_2geSF']")
        product_Names.append(name.text.split(maxsplit=1)[1:])
        
    except:
        product_Names.append('-')
        
    try:
        age = driver.find_element_by_xpath("//ul[@class = '_2KO13']/li[9]/strong[1]")
        Years.append(age.text.split(maxsplit = 1)[1:])
        
    except:
        Years.append('-')
        
    try:
        gas = driver.find_element_by_xpath("//ul[@class = '_2KO13']/li[4]/strong[1]")
        fuels.append(gas.text)
    
    except:
        fuels.append('-')
        
    try:
        dist = driver.find_element_by_xpath("//ul[@class = '_2KO13']/li[3]/strong[1]")
        kms_drivens.append(dist.text.split(' ')[0])
        
    except:
        kms_drivens.append('-')
        
    try:
        own = driver.find_element_by_xpath("//ul[@class = '_2KO13']/li[2]/strong[1]").text.split(' ')[0]
        ownerss.append(own)
        
    except:
        ownerss.append('-')
        
    try:
        gear = driver.find_element_by_xpath("//ul[@class = '_2KO13']/li[6]/strong[1]").text
        transmissions.append(gear)
        
    except:
        transmissions.append('-')
        
    try:
        cost = driver.find_element_by_xpath("//div[@class = 'text-right g-hPT']/strong[1]")
        prices.append(cost.text)
        
    except:
        prices.append('-')

In [140]:
cars1 = pd.DataFrame({})
cars1['name'] = product_Names
cars1['year'] = Years
cars1['selling_price'] = prices
cars1['Km_driven'] = kms_drivens
cars1['fuel'] = fuels
cars1['Transmission'] = transmissions
cars1['owner'] = ownerss

In [150]:
cars1.sample(5)

,name,year,selling_price,Km_driven,fuel,Transmission,owner
685,[Maruti Ciaz VXI MANUAL],[2015],"₹5,05,199","33,936",Petrol,MANUAL,1st
1561,[Hyundai i10 ERA 1.1 IRDE MANUAL],[2009],"₹1,71,099","1,19,014",Petrol,MANUAL,3rd
1135,[Ford Ecosport 1.5 TDCI TITANIUM PLUS MANUAL],[2018],"₹9,30,499","25,143",Diesel,MANUAL,1st
1049,[Maruti Swift LXI MANUAL],[2010],"₹3,69,199","46,079",Petrol,MANUAL,1st
840,[Maruti Ritz LXI MANUAL],[2010],"₹2,12,499","1,21,252",Petrol + CNG,MANUAL,1st

In [139]:
cars1.to_csv("Cars_Mumbai.csv",index=True)